### ISSUE TITLE
Developer tools - Network Emulation Trace Tools Extension in Browser Proposal 

### ISSUE THREAD

**Issue by sudeepdi** [w3c/web-networks#20]
## Description
Proposal: Network Emulation Trace Tools Extension in Browser Tools

This was presented in the WNIG Meeting on 9th March 2021. Refer to minutes of [meeting ](https://www.w3.org/2021/03/09-web-networks-minutes.html).

The proposal is the following:

- Browser extension to emulate network behavior over time from trace file 
- Load trace files for different wireless networks around the world
- Define a trace file specification that can be followed by all browsers
- Develop a trace collection tool to gather/create trace files
- Enable web application testing using trace based network emulation in browser

Slides presented are available [here](https://lists.w3.org/Archives/Public/public-networks-ig/2021Mar/att-0001/Network_Trace_Tools_at_W3C_v1.0.pdf).
Reference implementation with explanations are available [here](https://github.com/intel/lpp-network-trace).

## Call for Expression of Interest
If you are interested to join and engage in discussions on this topic, **kindly reply to this thread.**

We will consolidate and facilitate including interested members in upcoming meetings/emails to discuss the next steps, like create separate github issues for different sub-topics, start to track existing solutions, new proposals and formulate a plan on how to organize the work as a community group or taskforce with a defined scope.

 @gsimcard @DanDruta @chrisn @piersoh @yoavweiss @AutomatedTester  @dontcallmedom

**Comment by jsvennebring** [comment]
Sudeep, the Intel LPP team is, perhaps obvious, interested in this topic.

**Comment by dvelasquez** [comment]
I'm interested in this.

**Comment by acbegen** [comment]
I am interested in this as well, specifically with a focus on streaming applications.

**Comment by sudeepdi** [comment]
Thanks to all who expressed interest. We have now created a dedicated [github repo](https://github.com/w3c/network-emulation) for this topic.

Request you to share your ideas, feedback and continue the discussions there,
Ref:  https://github.com/w3c/network-emulation. 

Closing this thread.

@acbegen @jsvennebring @dvelasquez @gsimcard @DanDruta @chrisn @piersoh @AutomatedTester @dontcallmedom
